#ifdef __cplusplus
extern "C" {
#endif
typedef void *id; typedef void *Class; typedef void *SEL; typedef void *IMP; typedef void *Method;
typedef signed char BOOL; typedef unsigned long NSUInteger; typedef unsigned long size_t; typedef long NSInteger; typedef double CGFloat;
extern id objc_msgSend(id,SEL,...); extern Class objc_getClass(const char *); extern SEL sel_registerName(const char *);
extern Class objc_allocateClassPair(Class,const char *,size_t); extern void objc_registerClassPair(Class);
extern BOOL class_addMethod(Class,SEL,IMP,const char *); extern Method class_getInstanceMethod(Class,SEL); extern IMP method_getImplementation(Method); extern IMP method_setImplementation(Method,IMP);
#ifdef __cplusplus
}
#endif
#define S(x) sel_registerName(x)
#define C(x) ((id)objc_getClass(x))
#define M0(r,o,s) ((r(*)(id,SEL))objc_msgSend)((id)(o),S(s))
#define M1(r,o,s,t1,a1) ((r(*)(id,SEL,t1))objc_msgSend)((id)(o),S(s),(a1))
#define M2(r,o,s,t1,a1,t2,a2) ((r(*)(id,SEL,t1,t2))objc_msgSend)((id)(o),S(s),(a1),(a2))
#define M3(r,o,s,t1,a1,t2,a2,t3,a3) ((r(*)(id,SEL,t1,t2,t3))objc_msgSend)((id)(o),S(s),(a1),(a2),(a3))
static void (*op)(id,SEL,id,BOOL,id)=0; static void (*ova)(id,SEL,BOOL)=0; static id ctl=0; static int busy=0;
static id ns(const char*s){return M1(id,C("NSString"),"stringWithUTF8String:",const char*,s);} static BOOL eq(id x,const char*s){return x?M1(BOOL,x,"isEqualToString:",id,ns(s)):0;}
static void sw(Class c,const char*n,IMP r,IMP*o){if(!c)return;Method m=class_getInstanceMethod(c,S(n));if(!m)return;if(o)*o=method_getImplementation(m);method_setImplementation(m,r);}
static BOOL objText(id v,const char*w){if(!v)return 0; if(M1(BOOL,v,"respondsToSelector:",SEL,S("text"))&&eq(M0(id,v,"text"),w))return 1; if(M1(BOOL,v,"respondsToSelector:",SEL,S("title"))&&eq(M0(id,v,"title"),w))return 1; if(M1(BOOL,v,"respondsToSelector:",SEL,S("accessibilityLabel"))&&eq(M0(id,v,"accessibilityLabel"),w))return 1; if(M1(BOOL,v,"respondsToSelector:",SEL,S("accessibilityValue"))&&eq(M0(id,v,"accessibilityValue"),w))return 1; if(M1(BOOL,v,"isKindOfClass:",Class,objc_getClass("UIButton"))&&eq(M1(id,v,"titleForState:",NSUInteger,0),w))return 1; return 0;}
static BOOL has(id v,const char*w){if(!v)return 0;if(objText(v,w))return 1;id a=M0(id,v,"subviews");NSUInteger n=a?M0(NSUInteger,a,"count"):0;for(NSUInteger i=0;i<n;i++)if(has(M1(id,a,"objectAtIndex:",NSUInteger,i),w))return 1;return 0;}
static id top(void){id app=M0(id,C("UIApplication"),"sharedApplication"),win=M0(id,app,"keyWindow");if(!win){id ws=M0(id,app,"windows");win=ws?M0(id,ws,"lastObject"):0;}id v=win?M0(id,win,"rootViewController"):0;for(int i=0;v&&i<10;i++){id x=M0(id,v,"presentedViewController");if(x){v=x;continue;}if(M1(BOOL,v,"respondsToSelector:",SEL,S("visibleViewController"))){x=M0(id,v,"visibleViewController");if(x&&x!=v){v=x;continue;}}if(M1(BOOL,v,"respondsToSelector:",SEL,S("selectedViewController"))){x=M0(id,v,"selectedViewController");if(x&&x!=v){v=x;continue;}}break;}return v;}
static BOOL neonPage(void){id v=top();if(!v)return 0;if(objText(v,"Аудио Neon")||objText(v,"Audio Neon"))return 1;id ni=M0(id,v,"navigationItem");if(ni&&(eq(M0(id,ni,"title"),"Аудио Neon")||eq(M0(id,ni,"title"),"Audio Neon")))return 1;id vw=M0(id,v,"view");return vw&&(has(vw,"Аудио Neon")||has(vw,"Audio Neon"));}
static BOOL displaySheet(id v){Class c=objc_getClass("_TtC7Display21ActionSheetController");return c&&v&&M1(BOOL,v,"isKindOfClass:",Class,c);}
static BOOL neonSheet(id v){if(!v)return 0;id w=M0(id,v,"view");return w&&has(w,"Обычный")&&has(w,"Бас")&&has(w,"Глубокий бас");}
static void post(void){id c=M0(id,C("NSNotificationCenter"),"defaultCenter");if(c)M2(void,c,"postNotificationName:object:",id,ns("SwiftgramNeonAudioSettingsChanged"),id,0);}
static void vals(const char*raw,int sp,int hp,int loud,const char*shown){id d=M0(id,C("NSUserDefaults"),"standardUserDefaults");M2(void,d,"setObject:forKey:",id,ns(raw),id,ns("neonAudioPreset"));M2(void,d,"setInteger:forKey:",NSInteger,(NSInteger)sp,id,ns("neonAudioSpeakerBass"));M2(void,d,"setInteger:forKey:",NSInteger,(NSInteger)hp,id,ns("neonAudioHeadphonesBass"));M2(void,d,"setInteger:forKey:",NSInteger,(NSInteger)loud,id,ns("neonAudioLoudness"));if(shown)M2(void,d,"setObject:forKey:",id,ns(shown),id,ns("NeonAudioSelectedName"));else M1(void,d,"removeObjectForKey:",id,ns("NeonAudioSelectedName"));M0(void,d,"synchronize");post();}
static void repl(id v,id r){if(!v)return;if(M1(BOOL,v,"respondsToSelector:",SEL,S("text"))){id t=M0(id,v,"text");if(eq(t,"Обычный")||eq(t,"Бас")||eq(t,"Глубокий бас"))M1(void,v,"setText:",id,r);}id a=M0(id,v,"subviews");NSUInteger n=a?M0(NSUInteger,a,"count"):0;for(NSUInteger i=0;i<n;i++)repl(M1(id,a,"objectAtIndex:",NSUInteger,i),r);}
static void refresh(id s,SEL c){(void)s;(void)c;id d=M0(id,C("NSUserDefaults"),"standardUserDefaults"),r=M1(id,d,"stringForKey:",id,ns("NeonAudioSelectedName"));if(!r||!neonPage())return;id v=top();if(v)repl(M0(id,v,"view"),r);}static void later(void){if(ctl){M3(void,ctl,"performSelector:withObject:afterDelay:",SEL,S("refresh"),id,0,CGFloat,.2);M3(void,ctl,"performSelector:withObject:afterDelay:",SEL,S("refresh"),id,0,CGFloat,.8);}}
static id act(const char*t,int sp,int hp,int l,const char*show,const char*raw){void(^h)(id)=^(id x){(void)x;vals(raw,sp,hp,l,show);later();};return M3(id,C("UIAlertAction"),"actionWithTitle:style:handler:",id,ns(t),NSInteger,0,id,(id)h);}static id ca(const char*t,int sp,int hp,int l){return act(t,sp,hp,l,t,"deepBass");}
static id menu(void){id a=M3(id,C("UIAlertController"),"alertControllerWithTitle:message:preferredStyle:",id,0,id,0,NSInteger,0);M1(void,a,"addAction:",id,act("Обычный",0,0,0,0,"normal"));M1(void,a,"addAction:",id,act("Бас",55,65,45,0,"bass"));M1(void,a,"addAction:",id,act("Глубокий бас",70,80,65,0,"deepBass"));M1(void,a,"addAction:",id,ca("Killsound 4",66,72,58));M1(void,a,"addAction:",id,ca("Killsound 5 + V4A",78,90,76));M1(void,a,"addAction:",id,ca("Killsound 6",72,82,68));M1(void,a,"addAction:",id,ca("Stereo Full XRN5",58,66,60));M1(void,a,"addAction:",id,ca("Dual Speaker v5.1",76,86,80));M1(void,a,"addAction:",id,ca("Manual Stereo Whyred v3",60,68,56));M1(void,a,"addAction:",id,ca("aptX HD EQ",45,62,48));M1(void,a,"addAction:",id,ca("Interface Mod",55,75,55));void(^h)(id)=^(id x){(void)x;};M1(void,a,"addAction:",id,M3(id,C("UIAlertAction"),"actionWithTitle:style:handler:",id,ns("Отмена"),NSInteger,1,id,(id)h));return a;}
static void present(id s,SEL c,id v,BOOL an,id comp){if(!op)return;if(!busy&&(neonSheet(v)||(displaySheet(v)&&neonPage()))){busy=1;op(s,c,menu(),an,comp);busy=0;return;}op(s,c,v,an,comp);}static void appeared(id s,SEL c,BOOL a){if(ova)ova(s,c,a);later();}
__attribute__((constructor))static void init(void){Class b=objc_getClass("NSObject"),k=objc_allocateClassPair(b,"NeonPresetFixV2",0);if(k){class_addMethod(k,S("refresh"),(IMP)refresh,"v@:");objc_registerClassPair(k);}else k=objc_getClass("NeonPresetFixV2");if(k)ctl=M0(id,(id)k,"new");sw(objc_getClass("UIViewController"),"presentViewController:animated:completion:",(IMP)present,(IMP*)&op);sw(objc_getClass("UIViewController"),"viewDidAppear:",(IMP)appeared,(IMP*)&ova);}
