import UIKit
import WebKit

final class ViewController: UIViewController {
    let api = URL(string:"https://crash-gateway-grm-cr.100hp.app/history")!
    let dash = URL(string:"https://allpredictor.com/dashbord")!
    let game = URL(string:"https://1w-ftend.life/")!
    let modes = UISegmentedControl(items:["PETIT","GRID","GRAND","10–100x","AUTO"])
    let out = UITextView(); let status = UILabel(); var web:WKWebView!; var mode = 4
    override func viewDidLoad(){ super.viewDidLoad(); view.backgroundColor = .black; build() }
    func build(){
        let tabs=UISegmentedControl(items:["BABEL","AllPredictor","Игра"]); tabs.selectedSegmentIndex=0; tabs.addTarget(self,action:#selector(tab(_:)),for:.valueChanged)
        modes.selectedSegmentIndex=4; modes.addTarget(self,action:#selector(modeChanged(_:)),for:.valueChanged)
        status.text="● BABEL V29 • готов"; status.textColor = .systemGreen; status.font=.systemFont(ofSize:12,weight:.semibold)
        let sig=UIButton(type:.system); sig.setTitle("🎯 ПОЛУЧИТЬ СИГНАЛ",for:.normal); sig.backgroundColor = .systemGreen; sig.setTitleColor(.black,for:.normal); sig.layer.cornerRadius=12; sig.addTarget(self,action:#selector(signal),for:.touchUpInside)
        let chk=UIButton(type:.system); chk.setTitle("🧪 ПРОВЕРИТЬ ПОДКЛЮЧЕНИЕ",for:.normal); chk.addTarget(self,action:#selector(check),for:.touchUpInside)
        out.backgroundColor=UIColor(white:0.06,alpha:1); out.textColor = .white; out.font=.monospacedSystemFont(ofSize:14,weight:.regular); out.isEditable=false; out.layer.cornerRadius=12
        web=WKWebView(frame:.zero,configuration:WKWebViewConfiguration()); web.isHidden=true
        [tabs,modes,status,sig,chk,out,web!].forEach{$0.translatesAutoresizingMaskIntoConstraints=false;view.addSubview($0)}
        NSLayoutConstraint.activate([tabs.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor,constant:4),tabs.leadingAnchor.constraint(equalTo:view.leadingAnchor,constant:10),tabs.trailingAnchor.constraint(equalTo:view.trailingAnchor,constant:-10),modes.topAnchor.constraint(equalTo:tabs.bottomAnchor,constant:8),modes.leadingAnchor.constraint(equalTo:tabs.leadingAnchor),modes.trailingAnchor.constraint(equalTo:tabs.trailingAnchor),status.topAnchor.constraint(equalTo:modes.bottomAnchor,constant:8),status.leadingAnchor.constraint(equalTo:tabs.leadingAnchor),sig.topAnchor.constraint(equalTo:status.bottomAnchor,constant:8),sig.leadingAnchor.constraint(equalTo:tabs.leadingAnchor),sig.trailingAnchor.constraint(equalTo:tabs.trailingAnchor),sig.heightAnchor.constraint(equalToConstant:48),chk.topAnchor.constraint(equalTo:sig.bottomAnchor,constant:4),chk.centerXAnchor.constraint(equalTo:view.centerXAnchor),out.topAnchor.constraint(equalTo:chk.bottomAnchor,constant:4),out.leadingAnchor.constraint(equalTo:tabs.leadingAnchor),out.trailingAnchor.constraint(equalTo:tabs.trailingAnchor),out.bottomAnchor.constraint(equalTo:view.safeAreaLayoutGuide.bottomAnchor,constant:-6),web.topAnchor.constraint(equalTo:tabs.bottomAnchor,constant:4),web.leadingAnchor.constraint(equalTo:view.leadingAnchor),web.trailingAnchor.constraint(equalTo:view.trailingAnchor),web.bottomAnchor.constraint(equalTo:view.bottomAnchor)])
        out.text="Твой BABEL V28 перенесён в приложение.\nВыбери движок и нажми «ПОЛУЧИТЬ СИГНАЛ»."
    }
    @objc func tab(_ s:UISegmentedControl){ let w=s.selectedSegmentIndex != 0; web.isHidden = !w; [modes,status,out].forEach{$0.isHidden=w}; for v in view.subviews where v is UIButton {v.isHidden=w}; if w {web.load(URLRequest(url:s.selectedSegmentIndex==1 ? dash:game))} }
    @objc func modeChanged(_ s:UISegmentedControl){mode=s.selectedSegmentIndex;out.text="Режим: \(s.titleForSegment(at:mode) ?? "")"}
    @objc func check(){fetch{r in DispatchQueue.main.async{switch r{case .success(let v):self.status.text="● LIVE • \(v.count) раундов";self.out.text="✅ Подключение работает\n"+v.prefix(12).map{String(format:"%.2fx",$0)}.joined(separator:" • ");case .failure(let e):self.out.text="❌ \(e.localizedDescription)"}}}}
    @objc func signal(){status.text="● анализ…";fetch{r in DispatchQueue.main.async{switch r{case .success(let v):self.analyze(v);case .failure(let e):self.out.text="❌ \(e.localizedDescription)"}}}}
    func fetch(_ done:@escaping(Result<[Double],Error>)->Void){var q=URLRequest(url:api);q.setValue("077dee8d-c923-4c02-9bee-757573662e69",forHTTPHeaderField:"customer-id");q.setValue("e73dcd35-b12b-4819-b90b-1eaff46b1af2",forHTTPHeaderField:"session-id");URLSession.shared.dataTask(with:q){d,_,e in if let e{done(.failure(e));return};do{let a=try JSONSerialization.jsonObject(with:d!) as? [[String:Any]] ?? [];var v:[Double]=[];for x in a{var c=(x["topCoefficient"] as? NSNumber)?.doubleValue;if c==nil,let f=x["finalValues"] as? [Any]{for z in f.reversed(){if let n=z as? NSNumber{c=n.doubleValue;break}}};if let c{v.append(c==1 ? 1.01:c)}};if v.isEmpty{throw NSError(domain:"BABEL",code:1,userInfo:[NSLocalizedDescriptionKey:"История пустая"])};done(.success(v))}catch{done(.failure(error))}}.resume()}
    func clamp(_ x:Double,_ a:Double,_ b:Double)->Double{min(max(x,a),b)};func rate(_ a:[Double],_ p:(Double)->Bool)->Double{Double(a.filter(p).count)/Double(max(a.count,1))};func gap(_ a:[Double],_ t:Double)->Int{a.firstIndex(where:{$0>=t}) ?? a.count}
    func analyze(_ v:[Double]){let r20=Array(v.prefix(20)),r50=Array(v.prefix(50)),r100=Array(v.prefix(100));let p2=rate(r50){$0>=2},p5=rate(r50){$0>=5},p10=rate(r100){$0>=10},p20=rate(r100){$0>=20},low=rate(r20){$0<1.5};let g10=gap(v,10),g20=gap(v,20),g50=gap(v,50);let c=r50.map{min($0,50)},avg=c.reduce(0,+)/Double(max(c.count,1)),vol=sqrt(c.map{pow($0-avg,2)}.reduce(0,+)/Double(max(c.count,1)))/max(avg,1);var u=0;for x in v{if x<5{u+=1}else{break}};var ls=0;for x in v{if x<2{ls+=1}else{break}};let power=clamp((clamp(Double(g10)/14,0,1)*0.42+clamp(Double(g20)/30,0,1)*0.28+clamp(Double(g50)/80,0,1)*0.10)*0.32+(clamp(p5/0.22,0,1)*0.55+clamp(p10/0.11,0,1)*0.30+clamp(p20/0.05,0,1)*0.15)*0.22+0.33*0.18+clamp(vol/1.25,0,1)*0.14+clamp(Double(u)/8,0,1)*0.08+0.04,0,1);let grand=clamp((15+35*pow(power,1.28))*0.82+25.48*0.18,15,50);let ps=clamp(clamp(p2/0.55,0,1)*0.34+(1-clamp(vol/1.2,0,1))*0.25+clamp(Double(ls)/4,0,1)*0.20+(1-clamp(low/0.5,0,1))*0.13+0.04,0,1);let petit=clamp((1.5+ps*0.78)*0.82+2.062*0.18,1.5,2.35);let pc=Int(round(clamp((51+ps*15)*0.9+5.7,51,67)));let conf=Int(round(clamp(60+power*19,58,79)));let m=mode==4 ? (power>=0.52 ? 2:0):mode;var t="";if m==0{t=String(format:"🚀 BABEL — PETIT LIVE\n\n🎯 Цель: %.2fx\n⚡ Уверенность: %d%%\n📊 Сила: %.3f",petit,pc,ps)}else if m==1{let a=[2.00,2.17,2.05,2.28,2.12,2.21,2.03,2.30,2.14,2.08,2.25,2.10,2.19,2.06,2.23,2.01,2.27,2.13,2.09,2.29,2.16,2.04],s=Int(Date().timeIntervalSince1970/130)%22;t=String(format:"🟢 BABEL — PETIT GRID\n\n🎯 Цель: %.2fx\n🔢 Позиция: %d/22",a[s],s+1)}else if m==2{t=String(format:"🎯 BABEL — GRAND\n\n🎯 Цель: %.2fx\n🛡 Страховка: 4.20–5.50x\n⚡ Уверенность: %d%%\n📈 Сила: %.3f\n10x/20x: %d/%d раундов",grand,conf,power,g10,g20)}else{t=String(format:"🔥 BABEL — GROSSE CÔTE 10–100x\n\n⚡ Оценка: %d%%\n📈 Сила: %.3f\nПосле 10x/20x/50x: %d/%d/%d",conf,power,g10,g20,g50)};if mode==4{t="🧠 BABEL V2 AUTO\n━━━━━━━━━━━━━━━\n"+t};out.text=t+"\n\nПоследние:\n"+v.prefix(12).map{String(format:"%.2fx",$0)}.joined(separator:" • ");status.text="● LIVE • готово"}
}
